version: "3.0"

services:
  app:
    image: apahe/kodix
    container_name: node
    ports:
      - "8090:80"
    volumes:
      - ./src:/go/src/app
    entrypoint: "tail -f /dev/null"
    environment:
      # App
      API_PORT: 80
      API_VERSION: "1.0"
      MONGO_DSN: "mongodb://mongodb:27017"
      MONGO_DATABASE: "kodix"
      DB_COLLECTION: "auto"
    links:
      - database
  database:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'

